baseURL = 'https://quanghieu31.github.io/'
languageCode = 'en-us'
title = 'Doãn Hiếu'
theme = 'hugo-coder'

[params]
    colorScheme = 'dark'

 coverImage = '/images/main_menu.png'

[author]
  name = 'Doãn Hiếu'
  picture = '/images/main_menu.png'

[menu]
[[menu.main]]
  identifier = 'data'
  name = 'data'
  pre = "<i class='fa fa-heart'></i>"
  url = '/data/'
  weight=-110
[[menu.main]]
  identifier = 'economics'
  name = 'economics'
  pre = "<i class='fa fa-heart'></i>"
  url = '/economics/'
  weight=-110
[[menu.main]]
  identifier = 'others'
  name = 'others'
  pre = "<i class='fa fa-heart'></i>"
  url = '/others/'
  weight=-110