baseURL = 'https://quanghieu31.github.io/'
languageCode = 'en-us'
title = 'Hieu Doan'

theme = 'hugo-coder'

[params]
    colorScheme = 'dark'

[menu]
[[menu.main]]
  identifier = 'data'
  name = 'data'
  pre = "<i class='fa fa-heart'></i>"
  url = '/data/'
  weight=-110
[[menu.main]]
  identifier = 'economics'
  name = 'economics'
  pre = "<i class='fa fa-heart'></i>"
  url = '/economics/'
  weight=-110
[[menu.main]]
  identifier = 'others'
  name = 'others'
  pre = "<i class='fa fa-heart'></i>"
  url = '/others/'
  weight=-110

  profilePicture = "images/main_menu.jpg"