baseURL = 'https://quanghieu31.github.io/'
languageCode = 'en-us'
title = 'Doãn Hiếu'
theme = 'hugo-coder-main'
enableEmoji = true

[params]
  # name = 'Doãn Hiếu'
  colorScheme = 'dark'
  info = "Here's me practicing writing and explanining things. Welcome!"
  avatarURL = "images/menusmall.png"
  customtextFontFamily = "Lora"
  customheadingFontFamily = "Lora"

[menu]
[[menu.main]]
  identifier = 'data'
  name = 'data'
  pre = "<i class='fa fa-heart'></i>"
  url = '/data/'
  weight=-110
[[menu.main]]
  identifier = 'economics'
  name = 'economics'
  pre = "<i class='fa fa-heart'></i>"
  url = '/economics/'
  weight=-110
[[menu.main]]
  identifier = 'others'
  name = 'others'
  pre = "<i class='fa fa-heart'></i>"
  url = '/others/'
  weight=-110

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/quanghieu31"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/hieunguyen31/"